### ISSUE TITLE
Doesn't compile on XUbuntu+i3 14.04

### ISSUE THREAD

**Issue by SuperCuber** [geommer/yabar#111]
At the "make" step of the installation:

cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-52-g94e05dd\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_draw.o src/ya_draw.c
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-52-g94e05dd\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_exec.o src/ya_exec.c
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-52-g94e05dd\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_main.o src/ya_main.c
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-52-g94e05dd\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/ya_parse.o src/ya_parse.c
src/ya_parse.c: In function ‘ya_config_parse’:
src/ya_parse.c:746:3: warning: implicit declaration of function ‘config_setting_lookup’ [-Wimplicit-function-declaration]
   blklist_set = config_setting_lookup(curbar_set, "block-list");
   ^
src/ya_parse.c:746:15: warning: assignment makes pointer from integer without a cast [enabled by default]
   blklist_set = config_setting_lookup(curbar_set, "block-list");
               ^
src/ya_parse.c:765:15: warning: assignment makes pointer from integer without a cast [enabled by default]
    curblk_set = config_setting_lookup(curbar_set, blkstr);
               ^
cc -std=c99 -Iinclude -pedantic -Wall -Os `pkg-config --cflags pango pangocairo libconfig gdk-pixbuf-2.0` -DVERSION=\"0.4.0-52-g94e05dd\" -D_POSIX_C_SOURCE=199309L -DYA_INTERNAL -DYA_DYN_COL -DYA_ENV_VARS -DYA_INTERNAL_EWMH -DYA_ICON -DYA_NOWIN_COL -DYA_MUTEX -DYA_VAR_WIDTH  -c -o src/intern_blks/ya_intern.o src/intern_blks/ya_intern.c
cc -o yabar src/ya_draw.o src/ya_exec.o src/ya_main.o src/ya_parse.o src/intern_blks/ya_intern.o -lxcb -lpthread -lxcb-randr -lxcb-ewmh `pkg-config --libs pango pangocairo libconfig gdk-pixbuf-2.0`
src/ya_parse.o: In function `ya_config_parse':
ya_parse.c:(.text+0x4ae): undefined reference to `config_setting_lookup'
ya_parse.c:(.text+0xb2a): undefined reference to `config_setting_lookup'
collect2: error: ld returned 1 exit status
make: *** [yabar] Error 1

**Comment by jacksgt** [comment]
As explained in the [README](https://github.com/geommer/yabar#installation), Ubuntu 14.04 has an old version of libconfig (namely 1.4.x). You need to compile with an extra option:
```
export CPPFLAGS=-DOLD_LIBCONFIG
make
```

----------------------

Also, next time please put your code and/or output inside  [Markdown code blocks](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) like so:

\`\`\`
echo 'Hello World'
\`\`\`

which is magically formatted as:

```
echo 'Hello World'
```

It makes reading the output a lot easier :-)

**Comment by SuperCuber** [comment]
And how did you insert ``` without it getting formatted? MAGIC?!!?!?

And I went to i3blocks and spent enough time configuring it that it will be a waste if I go back so thanks for the help but I won't need it :(

**Comment by jacksgt** [comment]
You're welcome :-)

-----------------------
Also:
```
\`\`\`
echo 'Hello World'
\`\`\`
```
gets parsed into this:
\`\`\`
echo 'Hello World'
\`\`\`
Obligatory Reddit Thread:
https://www.reddit.com/r/AskReddit/comments/cmwov/hey_reddit_what_tattoos_do_you_have/c0tpyls?context=3
